# Generated by Django 2.2.12 on 2020-05-27 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='video_url',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
