# Generated by Django 2.2.12 on 2020-05-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='edition',
            name='edit_img',
            field=models.ImageField(blank=True, upload_to='edition_img'),
        ),
    ]
